export type IColors =
  | "main"
  | "main-dark"
  | "main-extra-dark"
  | "dark-01"
  | "dark-02"
  | "dark-03"
  | "dark-04"
  | "light-01"
  | "light-02"
  | "light-03"
  | "light-04"
  | "error"
  | "error-light"
  | "error-dark"
  | "success"
  | "success-light"
  | "success-dark";
